### ISSUE TITLE
Assertion failed: !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by mdnahas** [boltgolt/howdy#126]
Just installed.  Ran "sudo howdy add" and "sudo howdy -U mike add" and get same error:

Adding face model for the user mike
Enter a label for this new model [Initial model] (max 24 characters): Mike
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Please look straight into the camera
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 89, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 147, in <module>
    gsframe = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
**cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'**

The install seemed to go well.  I did see a warning about ~/.cache/pip/http and ~/cache/pip not being owned by root.  (Should install have been done with "sudo -H"?)   When the install asked me if "IR illuminators were active" (or something like that), I saw some red LEDs flashing next to the webcam, so I answered "y".  Did I make a mistake with that?

It's a brand new system.  I haven't done anything with python yet.  Maybe a dependence is missing?

----
Hardware:
Dell XPS 13 (model: 9370)

Linux distribution (if applicable):
Ubuntu 18.04

Howdy version:
howdy/bionic,bionic,now 2.5.0 all [installed]

**Comment by mdnahas** [comment]
After further searching, I got this link:
[https://www.reddit.com/r/linux4noobs/comments/8u5z35/dell_xps_13_9370_ir_camera_drivers_for_linux/](https://www.reddit.com/r/linux4noobs/comments/8u5z35/dell_xps_13_9370_ir_camera_drivers_for_linux/)

It says Ubuntu 18.04 does not have the drivers for the IR camera.  I f*%^ing bought a computer with Ubuntu installed at the factory BECAUSE it should have all the drivers.  I'm pissed.  

The link says that if I recompile the kernel, the drivers will work.  But, even then, howdy doesn't support the 8-bit format coming from the camera.  I'd ask you to support the camera's format, but since I can't even get the f^&*ing drivers for the camera, it probably isn't worth doing.  The link contains the author-admits-kludgy code to do something similar to Howdy, if people want to recompile the kernel and work with the 8-bit file format.

**Comment by mdnahas** [comment]
The Arch Wiki says Howdy works for my Dell XPS 13 (model 9370).  It looks like the device driver for the IR camera made it into the kernel, but neither Ubuntu 18.04 nor Ubuntu 18.10 has the change.  I'll have to wait until Ubuntu 19.04 ... or switch to Arch.
I've uninstalled Howdy, but I assume the value of "ret" is False.  That's what the documentation says.  I think ret=False just means that an image couldn't be read from the camera - it doesn't necessarily mean they'll have my problem.  So, you should check the value of "ret", but your warning should be something like "an image couldn't be read.  Is /dev/video... the IR camera?" (rather than something like "You have a Dell XPS 13 (model 9370) and lazy m*****f***ing Dell didn't write a device driver for your IR camera.")
BTW, I had a feeling the device wasn't the IR camera when I used "cheese" with it.  "cheese" returned a normal photo.  In your documentation, you might want to say that if it is the IR camera, "cheeze" might look something like this: 


[Image stolen from https://blogs.gnome.org/jamesh/2017/10/22/thinkpad-infrared-camera/  ]
Do you have a wiki page where users can write up their experience?  The Arch page was very helpful in diagnosing that there was an issue.  (https://wiki.archlinux.org/index.php/Dell_XPS_13_(9370)#Infrared_camera)  
Thanks for the quick response and good luck.  I hope to use Howdy as soon as I can get the IR camera working!!!
Mike



    On Tuesday, January 22, 2019, 4:29:29 PM CST, boltgolt <notifications@github.com> wrote:  
 
 
Unfortunately this is a problem for a lot of people, IR camera support just isn't high on the list of priorities as most users will never use them. Until a working driver and kernel have been released i don't see anything i can do about it.

I will add a more robust check if the read frames actually make sense, what does ret return for you?
