### ISSUE TITLE
EOFError: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by bingws** [boltgolt/howdy#157]
I installed it the following way and got an error on Ubuntu16.04 Desktop.
installation method：
```
sudo add-apt-repository ppa:boltgolt/howdy
sudo apt update
sudo apt install howdy
```
At the last step, an error occurred:
```
Traceback (most recent call last):
  File "/var/lib/dpkg/info/howdy.postinst", line 146, in <module>
    tf.extract(item, "/tmp")
  File "/usr/lib/python3.5/tarfile.py", line 2038, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2108, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.5/tarfile.py", line 2156, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)
  File "/usr/lib/python3.5/tarfile.py", line 241, in copyfileobj
    buf = src.read(BUFSIZE)
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
dpkg: error processing package howdy (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up dh-strip-nondeterminism (0.015-1) ...
Setting up debhelper (9.20160115ubuntu3) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Errors were encountered while processing:
 howdy
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
@boltgolt

**Comment by bingws** [comment]
> I installed it the following way and got an error on Ubuntu16.04 Desktop.
> installation method：
> 
> ```
> sudo add-apt-repository ppa:boltgolt/howdy
> sudo apt update
> sudo apt install howdy
> ```
> At the last step, an error occurred:
> 
> ```
> Traceback (most recent call last):
>   File "/var/lib/dpkg/info/howdy.postinst", line 146, in <module>
>     tf.extract(item, "/tmp")
>   File "/usr/lib/python3.5/tarfile.py", line 2038, in extract
>     numeric_owner=numeric_owner)
>   File "/usr/lib/python3.5/tarfile.py", line 2108, in _extract_member
>     self.makefile(tarinfo, targetpath)
>   File "/usr/lib/python3.5/tarfile.py", line 2156, in makefile
>     copyfileobj(source, target, tarinfo.size, ReadError)
>   File "/usr/lib/python3.5/tarfile.py", line 241, in copyfileobj
>     buf = src.read(BUFSIZE)
>   File "/usr/lib/python3.5/gzip.py", line 274, in read
>     return self._buffer.read(size)
>   File "/usr/lib/python3.5/_compression.py", line 68, in readinto
>     data = self.read(len(byte_view))
>   File "/usr/lib/python3.5/gzip.py", line 480, in read
>     raise EOFError("Compressed file ended before the "
> EOFError: Compressed file ended before the end-of-stream marker was reached
> dpkg: error processing package howdy (--configure):
>  subprocess installed post-installation script returned error exit status 1
> Setting up dh-strip-nondeterminism (0.015-1) ...
> Setting up debhelper (9.20160115ubuntu3) ...
> Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
> Rebuilding /usr/share/applications/bamf-2.index...
> Processing triggers for libc-bin (2.23-0ubuntu10) ...
> Errors were encountered while processing:
>  howdy
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```
> @boltgolt
