### ISSUE TITLE
Pixel format of incoming image is unsupported by OpenCV

### ISSUE THREAD

**Issue by gdenn** [boltgolt/howdy#159]
howdy!

i tried to add my face with my Dell XPS 13 9370 Laptop using the howdy cli
```
sudo howdy add
```

Unfortunately i receive an error message indicating that my pixel format in not supported:
```
Adding face model for the user gdenn
Enter a label for this new model [Initial model] (max 24 characters): gdenn
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV

Please look straight into the camera
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 89, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 147, in <module>
    gsframe = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

Here is my output for `v4l2-ctl --list-formats`:
```
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2
```

If i am not mistaken you only support FFMPG and not MJPG and that is causing the problem. Do you see any chance i can run howdy with my ir camera? :)

best,
Dennis

----

Linux distribution: Ubuntu 18.04

Howdy version: 2.5.0

**Comment by boltgolt** [comment]
Take a look at [#88](https://github.com/boltgolt/howdy/issues/88#issuecomment-457708769)
