### ISSUE TITLE
Login Shows unknown error 1 | sudo -i also not working

### ISSUE THREAD

**Issue by vigneshgr8** [Boltgolt/howdy#31]
Traceback (most recent call last):
  File "/lib/security/howdy/compare.py", line 116, in <module>
    face_encodings = face_recognition.face_encodings(frame)
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 199, in face_encodings
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="small")
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 153, in _raw_face_landmarks
    face_locations = _raw_face_locations(face_image)
  File "/usr/local/lib/python3.6/dist-packages/face_recognition/api.py", line 102, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
RuntimeError: The stride of the 3rd dimension (the channel dimension) of the numpy array must be 1
Unknown error: 1

**This is the error i get when i run sudo -i and then it asks me for the password as usual.
FYI: my laptop doesn't have an IR emitter, could that be the issue?**
The test command works after i inserted that line into evironments and it does detect my face.

**Comment by Boltgolt** [comment]
I accidentally closed issue #30 which has a fix, i'll push an update somewhere in the following days.
