### ISSUE TITLE
Unable to install under Linux Mint 19.3 (Ubuntu 18) - CMAKE error

### ISSUE THREAD

**Issue by pwozniak89** [boltgolt/howdy#325]
Hi,

I tried many times to install howdy on my laptop and i have always the same problem during dlib building...
I use ppa to install howdy and run the command sudo -H apt install howdy

The first configurations steps works great (dependencies, IR camera check, upgrade of pip to the last version, download of data files, download of dlib)
But when it tries to build dlib the error occurs : 

>  >>> Building dlib
> 
> running install
> running bdist_egg
> running egg_info
> creating dlib.egg-info
> writing dlib.egg-info/PKG-INFO
> writing dependency_links to dlib.egg-info/dependency_links.txt
> writing top-level names to dlib.egg-info/top_level.txt
> writing manifest file 'dlib.egg-info/SOURCES.txt'
> package init file 'dlib/__init__.py' not found (or not a regular file)
> reading manifest file 'dlib.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'dlib.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> Building extension for Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
> Invoking CMake setup: 'cmake /tmp/dlib-19.16/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/dlib-19.16/build/lib.linux-x86_64-3.6 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_BUILD_TYPE=Release'
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is unknown
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> **CMake Error in CMakeLists.txt:
>   No CMAKE_CXX_COMPILER could be found.
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
>   to the compiler, or to the compiler name if it is in the PATH.
> 
> 
> -- Configuring incomplete, errors occurred!**
> See also "/tmp/dlib-19.16/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
> See also "/tmp/dlib-19.16/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".**
> Traceback (most recent call last):
>   File "setup.py", line 257, in <module>
>     'Topic :: Software Development',
>   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
>     self.do_egg_install()
>   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
>     self.run_command('bdist_egg')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
>     self.run_command(cmdname)
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
>     self.build()
>   File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
>     self.run_command('build_ext')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "setup.py", line 133, in run
>     self.build_extension(ext)
>   File "setup.py", line 170, in build_extension
>     subprocess.check_call(cmake_setup, cwd=build_folder)
>   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '/tmp/dlib-19.16/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/dlib-19.16/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

I can't access log files "/tmp/dlib-19.16/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log" and "/tmp/dlib-19.16/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log" as they are surely remove by the end of installation process.

I think the problem is cmake...
Please could you help me
_Sorry I'm French and my English isn't always perfect..._

**Comment by pwozniak89** [comment]
Sorry for the inconvenience but I found my issue myself...
g++ is missing to install dlib !!!
So I have run "sudo apt install build-essential" then "sudo pip3 install dlib" and that works !
