### ISSUE TITLE
No option 'force_mjpeg' in section: 'debug'

### ISSUE THREAD

**Issue by halcyoncheng** [Boltgolt/howdy#36]
Hi there, this is amazing and I really want to try it out. I am getting this issue after I do "sudo howdy add"

Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'force_mjpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 86, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 85, in <module>
    if config.get("debug", "force_mjpeg") == "true":
  File "/usr/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'force_mjpeg' in section: 'debug'

**Comment by Boltgolt** [comment]
Thanks for reporting! I've pushed an update to the PPA and you should be able to update to it somewhere in the next 24 hours.
