### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pip3'

### ISSUE THREAD

**Issue by JanChec** [Boltgolt/howdy#598]
```
FileNotFoundError: [Errno 2] No such file or directory: 'pip3'
```
occurs when installing from the repo, as per instruction for Ubuntu from the main GitHub page (added repo, updated, then the installation command like below). As result `howdy` is not installed as a command (`which howdy` returns nothing).

```
$ sudo apt install howdy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  nvidia-cuda-dev
The following NEW packages will be installed:
  howdy
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/38,9 kB of archives.
After this operation, 166 kB of additional disk space will be used.
Selecting previously unselected package howdy.
(Reading database ... 214619 files and directories currently installed.)
Preparing to unpack .../archives/howdy_2.6.1_all.deb ...
Starting IR camera check...

Trying "Integrated Camera: Integrated I"
One of your cameras should now be on.
Did your IR emitters turn on? [y/N]: y

Starting certainty auto config...


After detection, Howdy knows how certain it is that the match is correct.
How certain Howdy needs to be before authenticating you can be customized.

F: Fast.
Allows more fuzzy matches, but speeds up the scanning process greatly.

B: Balanced.
Still relatively quick detection, but might not log you in when further away.

S: Secure.
The safest option, but will take much longer to authenticate you.

You can always change this setting in the config.
What profile would you like to use? [f/b/s]: s

Unpacking howdy (2.6.1) ...
Setting up howdy (2.6.1) ...

>>> Upgrading pip to the latest version

Traceback (most recent call last):
  File "/var/lib/dpkg/info/howdy.postinst", line 110, in <module>
    handleStatus(sc(["pip3", "install", "--upgrade", "pip"]))
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip3'
dpkg: error processing package howdy (--configure):
 installed howdy package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.4-2) ...
Errors were encountered while processing:
 howdy
E: Sub-process /usr/bin/dpkg returned an error code (1)
$ which pip3
/usr/local/bin/pip3
$ pip3 --version
pip 21.3 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)

```

----

I've searched for similar issues already, and my issue has not been reported yet. :)

Linux distribution (if applicable): Ubuntu 21.04

Howdy version (`sudo howdy version`): 2.6.1

**Comment by expl0r3rgu1** [comment]
Same issue on Pop OS

**Comment by jxn0** [comment]
I also got this on Ubuntu 21.10 the second time I installed it. Worked first time, but when I uninstalled it and installed it again it failed.

**Comment by yingmanwumen** [comment]
save in Debian 5.10

**Comment by Onion2222** [comment]
> I also got this on Ubuntu 21.10 the second time I installed it. Worked first time, but when I uninstalled it and installed it again it failed.
Same problem, solved by doing:
`sudo apt remove --purge howdy`
`sudo apt install --reinstall python3-pip`
`sudo apt install howdy`
It works now after a complete re-installation of howdy, I don't know what was wrong... Maybe the path to pip3 but I'm not sure and didn't check...

**Comment by MrConorAE** [comment]
I think I might know what's going on: immediately before the install crashes, pip says
```
WARNING: The scripts pip, pip3 and pip3.9 are installed in /usr/local/bin which is not on PATH. 
```
Maybe it can't find pip3 because it's, as pip says, not on the PATH by default?

**Comment by MrConorAE** [comment]
Added `/usr/local/bin` to PATH, no effect. :/

**Comment by MrConorAE** [comment]
Added `/usr/local/bin` to PATH, no effect. :/

Also, for me, `which pip3` returns `/usr/local/bin//pip3`. Is that double slash causing side effects? 
If I reinstall pip, it changes back to `/usr/bin` - this only happens after Howdy force-installs pip again (during the "upgrading pip to the latest version" step)

**Comment by albrtctm** [comment]
@vslm698-p thanks man, this works for me: sudo ln -sv $(which pip3) /usr/bin/pip3

**Comment by liqi001** [comment]
`sudo pip3 list`
Here, it is an error caused by my insufficient permission.

**Comment by egberts** [comment]
same issue on Debian 11

**Comment by alexanderLinear** [comment]
In a particular environment i only have user rights - so i am using the "--user" install option within pip.
But even then such an install will still fail for me with that message (along with some calls stacks):

`FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'`

If that binary is not there, then its not there and the tooling should not fault but only warn about that - at least my best case of understanding for the moment.
