### ISSUE TITLE
Howdy does not pickup dlib on Fedora 34

### ISSUE THREAD

**Issue by deepu105** [Boltgolt/howdy#604]
When running howdy add I get the below output. Dlib is installed on the system.

```
❯ sudo howdy add
[sudo] password for deepu: 
No module named 'dlib'

Can't import the dlib module, check the output of
pip3 show dlib

❯ pip3 show dlib        
Name: dlib
Version: 19.22.1
Summary: A toolkit for making real world machine learning and data analysis applications
Home-page: https://github.com/davisking/dlib
Author: Davis King
Author-email: davis@dlib.net
License: Boost Software License
Location: /home/deepu/.local/lib/python3.9/site-packages
Requires: 
Required-by: 

```

_Originally posted by @deepu105 in https://github.com/boltgolt/howdy/issues/596#issuecomment-953729851_

**Comment by realcomplex** [comment]
Same problem on Fedora. Except dlib wasn't even installed (and I'm running into errors trying to get pip3 to install it).

**Comment by realcomplex** [comment]
Actually, I installed dlib as root (`sudo pip3 install dlib`) and that worked for me.

**Comment by deepu105** [comment]
Nice that works for me too but now I have another issue as my primary
camera is not being detected

**Comment by realcomplex** [comment]
It looks like installing howdy on Fedora doesn't automatically set the camera device in the configuration file, did you do that already? `sudo howdy config` and then set `device_path` to the right device (`/dev/video2` for me).

**Comment by realcomplex** [comment]
Yeah.... The Fedora package seems to not quite work "out of the box" yet. It also doesn't seem to include any pam configuration, so I'm still actually trying to get sudo, gdm, etc. to use howdy.

**Comment by deepu105** [comment]
Do post your setup if you manage to get it working

**Comment by realcomplex** [comment]
I have found that the package at https://copr.fedorainfracloud.org/coprs/principis/howdy/ works much better (dlib included as dependency, so solves this issue), and includes good instructions. I had to follow all the additional configurations suggested there (set video device in config file, configure pam, fix selinux permissions) and also install `linux-enable-ir-emitter` (https://github.com/EmixamPP/linux-enable-ir-emitter), but now it works!

@boltgolt, seeing https://discussion.fedoraproject.org/t/luya-howdy/3454/10, would it be an idea to link to the principis/howdy copr instead for Fedora installation?

**Comment by HemanthChodisetti** [comment]
> sudo pip3 install dlib
 Recieved this error code on Fedora 35
root@fedora /h/hemanth# sudo pip3 install dlib
Collecting dlib
  Using cached dlib-19.22.1.tar.gz (7.4 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7oj5pa0s
       cwd: /tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/
  Complete output (56 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
  Invoking CMake setup: 'cmake /tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/build/lib.linux-x86_64-3.10 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_BUILD_TYPE=Release'
  -- The C compiler identification is GNU 11.2.1
  -- The CXX compiler identification is unknown
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  CMake Error at CMakeLists.txt:14 (project):
    No CMAKE_CXX_COMPILER could be found.
  
    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py", line 222, in <module>
      setup(
    File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.10/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.10/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib64/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib64/python3.10/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py", line 134, in run
      self.build_extension(ext)
    File "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py", line 171, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/build/lib.linux-x86_64-3.10', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pxi37574/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.10/dlib
         cwd: /tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/
    Complete output (58 lines):
    running install
    running build
    running build_py
    package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
    Invoking CMake setup: 'cmake /tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/build/lib.linux-x86_64-3.10 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is GNU 11.2.1
    -- The CXX compiler identification is unknown
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    CMake Error at CMakeLists.txt:14 (project):
      No CMAKE_CXX_COMPILER could be found.
    
      Tell CMake where to find the compiler by setting either the environment
      variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
      to the compiler, or to the compiler name if it is in the PATH.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py", line 222, in <module>
        setup(
      File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.10/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.10/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.10/distutils/command/install.py", line 579, in run
        self.run_command('build')
      File "/usr/lib64/python3.10/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.10/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.10/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py", line 134, in run
        self.build_extension(ext)
      File "/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py", line 171, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/build/lib.linux-x86_64-3.10', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6z_x6lhf/dlib_dc1b8d97ab22422b91c4e4df0fa51738/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pxi37574/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.10/dlib Check the logs for full command output.

**Comment by boltgolt** [comment]
@realcomplex updating the readme, thanks!
