### ISSUE TITLE
Howdy cannot use an incomplete config.ini

### ISSUE THREAD

**Issue by fufexan** [boltgolt/howdy#761]
I'm writing a [NixOS module for Howdy](https://github.com/NixOS/nixpkgs/pull/216245), and I'm letting the user define the Howdy config as a nix expression that gets translated to ini and placed in `/etc/howdy/config.ini`. While doing this, I have looked through the code and found that fallbacks are set, so I assumed they were for values that do not appear in the config file. However, when using this `config.ini`:

```ini
[core]
no_confirmation=true
[debug]
end_report=true
[video]
dark_threshold=90
```

Howdy gives me errors:
```py
sudo -E howdy test
Traceback (most recent call last):
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/configparser.py", line 791, in get
    value = d[option]
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'recording_plugin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/current-system/sw/bin/howdy", line 120, in <module>
    import cli.test
  File "/nix/store/yiyrf0igvkax54spw0lqpgrwfr5gyq8g-howdy-unstable-2023-02-28/lib/security/howdy/cli/test.py", line 24, in <module>
    if config.get("video", "recording_plugin") != "opencv":
  File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/configparser.py", line 794, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'recording_plugin' in section: 'video'
```

Is it possible to have an incomplete config file and have Howdy take care of the missing options?

**Comment by boltgolt** [comment]
For sure, we should really enforce that every config option (except maybe device?) has a default value. Preferably a very safe value, maybe even on theore cautious side than the default config is. 

If you or anyone would like to go through and add defaults to each config call that would be very appreciated!
