### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (10,360,640,3) (0,) 

### ISSUE THREAD

**Issue by SDNick484** [boltgolt/howdy#835]
_Please describe the issue in as much detail as possible, including any errors and traces._
_If your issue is a camera issue, be sure to also post the image generated by running `sudo howdy snapshot`._

When trying to run either sudo howdy add or snapshot, I get a failure with the following traceback:
Traceback (most recent call last):
  File "/usr/bin/howdy", line 107, in <module>
    import cli.snap
  File "/lib64/security/howdy/cli/snap.py", line 21, in <module>
    video_capture.read_frame()
  File "/lib64/security/howdy/recorders/video_capture.py", line 76, in read_frame
    ret, frame = self.internal.read()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/lib64/security/howdy/recorders/ffmpeg_reader.py", line 109, in read
    if self.video == ():
       ^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (10,360,640,3) (0,) 

----

I've searched for similar issues already, and my issue has not been reported yet.

Hardware: Lenovo Thinkbook 14p G3 (AMD) 
Linux distribution (if applicable): Gentoo
Portage version: 3.11.5
FFmpeg version: 4.4.4
OpenCV version: 4.8.0
Howdy version (`sudo howdy version`): 2.6.1

**Comment by Nir82** [comment]
Have the same issue:

Please look straight into the camera
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 95, in <module>
    import cli.add
  File "/usr/lib/security/howdy/cli/add.py", line 129, in <module>
    frame, gsframe = video_capture.read_frame()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/security/howdy/recorders/video_capture.py", line 76, in read_frame
    ret, frame = self.internal.read()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/security/howdy/recorders/ffmpeg_reader.py", line 109, in read
    if self.video == ():
       ^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (10,720,1280,3) (0,)
