### ISSUE TITLE
Error running sudo howdy add

### ISSUE THREAD

**Issue by Nwhouse** [boltgolt/howdy#84]
Installed latest howdy on ubuntu 18.04 using provided instructions.
When I ran "sudo howdy add" I get the following error

Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 90, in <module>
    import cli.add
  File "/lib/security/howdy/cli/add.py", line 9, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by boltgolt** [comment]
Please look for existing issues before opening a new one, take a look at #32
