### ISSUE TITLE
Howdy opencv module not importing

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [boltgolt/howdy#841]
_Please describe the issue in as much detail as possible, including any errors and traces.

Hello, i am using: https://aur.archlinux.org/packages/howdy-beta-git
The issue i am getting is with the opencv-python module, a dependency of howdy

_If your issue is a camera issue, be sure to also post the image generated by running sudo howdy snapshot
```
[SpiderUnderUrBed@DaSpiderCave ~]$ sudo howdy add
[sudo] password for SpiderUnderUrBed: 
Traceback (most recent call last):
  File "/usr/lib/howdy/cli.py", line 98, in <module>
    import cli.add
  File "/usr/lib/howdy/cli/add.py", line 13, in <module>
    from recorders.video_capture import VideoCapture
  File "/usr/lib/howdy/recorders/video_capture.py", line 6, in <module>
    import cv2
ImportError: libabsl_die_if_null.so.2301.0.0: cannot open shared object file: No such file or directory
```

----

I've searched for similar issues already, and my issue has not been reported yet. ✅

Linux distribution (if applicable): Arch

Howdy version (`sudo howdy version`):
Howdy 3.0.0 BETA

**Comment by musikid** [comment]
Did you try to re-install `python-opencv`? It seems to be an issue not on Howdy side.
