### ISSUE TITLE
BrokenPipeError after enabling the "hotkey" RubberStamp

### ISSUE THREAD

**Issue by LightTreasure** [boltgolt/howdy#916]
I installed Howdy Beta from the Fedora COPR: https://copr.fedorainfracloud.org/coprs/principis/howdy-beta/

Configured for sudo and it works well by default.

Then I wanted to add a `hotkey` RubberStamp. However, after enabling it through the config file, authentication succeeds but I don't get a prompt to press a hotkey. On the terminal, I get the following error:

> Internal error in rubberstamp:
> Traceback (most recent call last):
>   File "/usr/lib/python3.12/site-packages/howdy/rubberstamps/__init__.py", line 160, in execute
>     result = instance.run()
>              ^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/howdy/rubberstamps/hotkey.py", line 24, in run
>     self.set_ui_text(time_string.format(int(time_left)), self.UI_TEXT)
>   File "/usr/lib/python3.12/site-packages/howdy/rubberstamps/__init__.py", line 23, in set_ui_text
>     return self.send_ui_raw(typedec + "=" + text)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/howdy/rubberstamps/__init__.py", line 37, in send_ui_raw
>     self.gtk_proc.stdin.flush()
> BrokenPipeError: [Errno 32] Broken pipe

Digging a bit deeper, I noticed that this was happening because the `howdy_gtk --start-auth-ui` fails to launch (I found out after setting `gtk_stdout` to `true`). Then I get the following extra output:

> Authorization required, but no authorization protocol specified
> 
> Authorization required, but no authorization protocol specified 
>
> Traceback (most recent call last):
>   File "/usr/lib/python3.12/site-packages/howdy-gtk/init.py", line 8, in <module>
>     import authsticky
>   File "/usr/lib/python3.12/site-packages/howdy-gtk/authsticky.py", line 158, in <module>
>     window = StickyWindow()
>              ^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/howdy-gtk/authsticky.py", line 33, in __init__
>     gtk.Window.__init__(self)
>   File "/usr/lib64/python3.12/site-packages/gi/overrides/Gtk.py", line 508, in __init__
>     raise RuntimeError(
> RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.

Looking further, I discovered that this is related to issue #878 . If I use the workaround specified by @principis in that issue (setting the DISPLAY and XAUTHORITY environment variables), I see the prompt and the RubberStamp works as expected. However, this is not a long term solution for me since the XAUTHORITY variable changes from one session to another. (I'm running KDE Plasma)

@principis mentioned in #878 and #879 that a more permanent solution is to modify the polkit policy. My install of Howdy-gtk via the COPR came with this fix (@principis maintains that repo), so it doesn't seem to be working for me.

Please let me know if you need any extra information!

----
Linux distribution (if applicable): Fedora 40

Howdy version (`sudo howdy version`): Howdy 3.0.0 BETA

**Comment by principis** [comment]
#879 only fixes the case when you're trying to run howdy-gtk yourself on X11. For security reasons, pkexec only runs the program in a minimal environment. Setting `org.freedesktop.policykit.exec.allow_gui` to true does retain the `$DISPLAY` and `$XAUTHORITY` variables such that howdy-gtk can connect to the display server. On Wayland this doesn't work as it doesn't allow other users access to the wayland socket. It's possible to "hack" around it with the root user by setting `WAYLAND_DISPLAY` to the full path of the socket and setting `XDG_RUNTIME_DIR` to some value (or just pass both those vars).  But these variables aren't passed by pkexec (I think), so it's not possible to implement this hack.

The issue here is a bit different. The `compare.py` script is spawned by the pam module with an empty environment ([source](https://github.com/boltgolt/howdy/blob/beta/howdy/src/pam/main.cc#L276-L277)). It would be possible to pass  `$DISPLAY` and `$XAUTHORITY` without issue as these are kept. This won't work on Wayland however as the `$WAYLAND_DISPLAY` and `$XDG_RUNTIME_DIR` are not kept by the sudoers plugin. (Yes you can configure it, but you really shouldn't)

In the ideal case someone figures out how to run the howdy-gtk popup properly under the current user when invoked by PAM.

My current laptop does not have IR camera's so I'm not really interested in working on this (and no time as usual). I do want to keep maintaining my copr repos, so feel free to mention me if changes are needed. I really hope this project will  someday reach a point where I can include it in Fedora.

**Comment by LightTreasure** [comment]
@principis Thanks so much for the detailed response! I think I'm going to keep this issue open in hopes of someone fixing it in the future. Meanwhile I think I'll continue to use howdy without the rubberstamp.

**Comment by scientiac** [comment]
Not a one-to-one fix, but I managed to fix it just for the console UI removing the howdy-gtk parts from __init__ as well as hotkey.py. I did take some help from AI to write remove things though. 

I didn't care for the nod style RubberStamp so removed it.

<img width="754" height="336" alt="Image" src="https://github.com/user-attachments/assets/ca74c277-e0cc-4912-bb0e-23832f12d3bb" />

## Here is what I am using:
`howdy-git` from AUR.

I had to intall `python-keyboard` and `python-elevate`(may not be required but, fixed running howdy-gtk as root without errors) from the AUR. 

Then change these files in `/usr/lib/howdy/rubberstamps`.

## __init__.py
```py
import sys
import os
import re

from i18n import _

from importlib.machinery import SourceFileLoader


class RubberStamp:
	"""Howdy rubber stamp"""

	UI_TEXT = "ui_text"
	UI_SUBTEXT = "ui_subtext"

	def set_ui_text(self, text, type=None):
		"""Convert an ui string to console output instead of GTK"""
		prefix = "[INFO]" if type == self.UI_TEXT else "[SUB] "
		
		# Only print if we have a GTK process or if we're in verbose mode
		if self.gtk_proc or getattr(self, 'verbose', False):
			print(f"{prefix} {text}")
		
		return True

	def send_ui_raw(self, command):
		"""Write raw command to console instead of howdy-gtk stdin"""
		if self.config.getboolean("debug", "verbose_stamps", fallback=False):
			print("Console command: " + command)

		# If we're connected to the ui (and it exists)
		if self.gtk_proc and hasattr(self.gtk_proc, 'stdin') and self.gtk_proc.stdin:
			try:
				# Add a newline because the ui reads per line
				command += " \n"
				
				# Send the command as bytes
				self.gtk_proc.stdin.write(bytearray(command.encode("utf-8")))
				self.gtk_proc.stdin.flush()

				# Write a padding line to force the command through any buffers
				self.gtk_proc.stdin.write(bytearray("P=_PADDING \n".encode("utf-8")))
				self.gtk_proc.stdin.flush()
			except (BrokenPipeError, OSError):
				# GTK UI is not available, just continue without UI
				if self.config.getboolean("debug", "verbose_stamps", fallback=False):
					print("GTK UI not available, continuing without UI feedback")
				pass


def execute(config, gtk_proc, opencv):
	verbose = config.getboolean("debug", "verbose_stamps", fallback=False)
	dir_path = os.path.dirname(os.path.realpath(__file__))
	installed_stamps = []

	# Go through each file in the rubberstamp folder
	for filename in os.listdir(dir_path):
		# Remove non-readable file or directories
		if not os.path.isfile(dir_path + "/" + filename):
			continue

		# Remove meta files
		if filename in ["__init__.py", ".gitignore"]:
			continue

		# Add the found file to the list of enabled rubberstamps
		installed_stamps.append(filename.split(".")[0])

	if verbose: print("Installed rubberstamps: " + ", ".join(installed_stamps))

	# Get the rules defined in the config
	raw_rules = config.get("rubberstamps", "stamp_rules")
	rules = raw_rules.split("\n")

	# Go through the rules one by one
	for rule in rules:
		rule = rule.strip()

		if len(rule) <= 1:
			continue

		# Parse the rule with regex
		regex_result = re.search(r"^(\w+)\s+([\w\.]+)\s+([a-z]+)(.*)?$", rule, re.IGNORECASE)

		# Error out if the regex did not match (invalid line)
		if not regex_result:
			print(_("Error parsing rubberstamp rule: {}").format(rule))
			continue

		type = regex_result.group(1)

		# Error out if the stamp name in the rule is not a file
		if type not in installed_stamps:
			print(_("Stamp not installed: {}").format(type))
			continue

		# Load the module from file
		module = SourceFileLoader(type, dir_path + "/" + type + ".py").load_module()

		# Try to get the class with the same name
		try:
			constructor = getattr(module, type)
		except AttributeError:
			print(_("Stamp error: Class {} not found").format(type))
			continue

		# Init the class and set common values
		instance = constructor()
		instance.verbose = verbose
		instance.config = config
		instance.gtk_proc = gtk_proc
		instance.opencv = opencv

		# Set some opensv shorthands
		instance.video_capture = opencv["video_capture"]
		instance.face_detector = opencv["face_detector"]
		instance.pose_predictor = opencv["pose_predictor"]
		instance.clahe = opencv["clahe"]

		# Parse and set the 2 required options for all rubberstamps
		instance.options = {
			"timeout": float(re.sub("[a-zA-Z]", "", regex_result.group(2))),
			"failsafe": regex_result.group(3) != "faildeadly"
		}

		# Try to get the class do declare its other config variables
		try:
			instance.declare_config()
		except Exception:
			print(_("Internal error in rubberstamp configuration declaration:"))

			import traceback
			traceback.print_exc()
			continue

		# Split the optional arguments at the end of the rule by spaces
		raw_options = regex_result.group(4).split() if regex_result.group(4) else []

		# For each of those optional arguments
		for option in raw_options:
			# Skip empty options
			if not option or "=" not in option:
				continue
				
			# Get the key to the left, and the value to the right of the equal sign
			key, value = option.split("=", 1)

			# Error out if a key has been set that was not declared by the module before
			if key not in instance.options:
				print("Unknown config option for rubberstamp " + type + ": " + key)
				continue

			# Convert the argument string to an int or float if the declared option has that type
			if isinstance(instance.options[key], int):
				value = int(value)
			elif isinstance(instance.options[key], float):
				value = float(value)

			instance.options[key] = value

		if verbose:
			print("Stamp \"" + type + "\" options parsed:")
			print(instance.options)
			print("Executing stamp")

		# Make the stamp fail by default
		result = False

		# Run the stamp code
		try:
			result = instance.run()
		except Exception:
			print(_("Internal error in rubberstamp:"))

			import traceback
			traceback.print_exc()
			continue

		if verbose: print("Stamp \"" + type + "\" returned: " + str(result))

		# Abort authentication if the stamp returned false
		if result is False:
			if verbose: print("Authentication aborted by rubber stamp")
			sys.exit(15)

	# This is outside the for loop, so we've run all the rules
	if verbose: print("All rubberstamps processed, authentication successful")

	# Exit with no errors
	sys.exit(0)
```

## hotkey.py
```py
import time
import sys
from i18n import _

# Import the root rubberstamp class
from rubberstamps import RubberStamp

class hotkey(RubberStamp):
    pressed_key = "none"
    
    def declare_config(self):
        """Set the default values for the optional arguments"""
        self.options["abort_key"] = "esc"
        self.options["confirm_key"] = "enter"
    
    def run(self):
        """Wait for the user to press a hotkey"""
        time_left = self.options["timeout"]
        
        # Calculate number of dots based on timeout (one dot per second)
        total_dots = int(time_left)
        current_dots = 0
        
        # Print initial message with space for dots in brackets
        message = _("Face Detected! {abort_key}/{confirm_key} ").format(
            abort_key=self.options["abort_key"], 
            confirm_key=self.options["confirm_key"]
        )
        print(f"{message}[{' ' * total_dots}]", end="", flush=True)
        
        # Try to import the keyboard module and tell the user to install the module if that fails
        try:
            import keyboard
        except Exception:
            print("\nMissing python `keyboard` module.")
            sys.exit(1)
        
        # Register hotkeys with the kernel
        keyboard.add_hotkey(self.options["abort_key"], self.on_key, args=["abort"])
        keyboard.add_hotkey(self.options["confirm_key"], self.on_key, args=["confirm"])
        
        # While we have not hit our timeout yet
        while time_left > 0:
            # Update dots display at the start of each second
            current_second = int(time_left)
            new_dots = total_dots - current_second
            
            if current_dots < new_dots:
                current_dots = new_dots
                # Move cursor back and print more dots within brackets
                print(f"\r{message}[{'.' * current_dots}{' ' * (total_dots - current_dots)}]", end="", flush=True)
            
            # Remove 0.1 seconds from the timer
            time_left -= 0.1
            
            # If the abort key was pressed while the loop was sleeping
            if self.pressed_key == "abort":
                time.sleep(1)
                # Completely clear the line before returning
                print(f"\r{' ' * (len(message) + total_dots + 2)}\r", end="", flush=True)
                return False
            
            # If confirm has pressed, return that auth can continue
            elif self.pressed_key == "confirm":
                # Completely clear the line before returning
                print(f"\r{' ' * (len(message) + total_dots + 2)}\r", end="", flush=True)
                return True
            
            # If no key has been pressed, wait for a bit and check again
            time.sleep(0.1)
        
        # Fill all dots when timeout is reached
        print(f"\r{message}[{'.' * total_dots}]", end="", flush=True)
        
        # When our timeout hits, either abort or continue based on failsafe or faildeadly
        result = not self.options["failsafe"]
        # Completely clear the line before returning
        print(f"\r{' ' * (len(message) + total_dots + 2)}\r", end="", flush=True)
        return result
    
    def on_key(self, type):
        """Called when the user presses a key"""
        self.pressed_key = type
```
 

The only problem that remains is, this is applied everywhere, so when you are not in a terminal setting, for e.g. on GDM, it doesn't show you any indication that the key-press is necessary to continue with the authentication. But this might be a good or a bad thing depending upon the person.
