### ISSUE TITLE
howdy on nixos

### ISSUE THREAD

**Issue by plytkachodnikowa** [boltgolt/howdy#917]
any chance this would ever be packaged for nixos? i could try to do that, but first i just want to make sure no one else is doing that too and actually getting some progress, so as to not waste my time

**Comment by Kansattica** [comment]
There's work on it in nixpkgs, but there's some stumbling blocks. https://github.com/NixOS/nixpkgs/pull/216245

**Comment by nek0d3r** [comment]
Looks like that got merged, but setup has an issue.

```
nixos🔒 on  main via ❄  impure (shell) took 56s 
❯ sudo howdy add
No face model folder found, creating one
Adding face model for the user nek0d3r
Enter a label for this new model [Model #0]: 
Traceback (most recent call last):
  File "/nix/store/k40fz5ddpqz717j7256blbrxcmhhpgvs-howdy-3.0.0/lib/howdy/cli.py", line 100, in <module>
    import cli.add
  File "/nix/store/k40fz5ddpqz717j7256blbrxcmhhpgvs-howdy-3.0.0/lib/howdy/cli/add.py", line 115, in <module>
    video_capture = VideoCapture(config)
  File "/nix/store/k40fz5ddpqz717j7256blbrxcmhhpgvs-howdy-3.0.0/lib/howdy/recorders/video_capture.py", line 35, in __init__
    if not os.path.exists(self.config.get("video", "device_path")):
                          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/j70z6hsrzd749h3n1zgm9l9nj4dlg94y-python3-3.13.14-env/lib/python3.13/configparser.py", line 819, in get
    d = self._unify_values(section, vars)
  File "/nix/store/j70z6hsrzd749h3n1zgm9l9nj4dlg94y-python3-3.13.14-env/lib/python3.13/configparser.py", line 1193, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'video'
```

I'm not sure if additional configuration is required for PAM.
