### ISSUE TITLE
Trying to authenticate: "NoSectionError: No section: 'core'"

### ISSUE THREAD

**Issue by jordanss1** [boltgolt/howdy#943]
Howdy works on the command line and is installed successfully but doesn't seem to be working when i use **sudo -i** as mentioned in the setup instructions. I check the auth.log file and I see this:

> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]: Traceback (most recent call last):
> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]:   File "/lib/security/howdy/pam.py", line 101, in pam_sm_authenticate
> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]:     return doAuth(pamh)
> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]:   File "/lib/security/howdy/pam.py", line 29, in doAuth
> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]:     if config.getboolean("core", "disabled"):
> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]:   File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]:     v = self.get(section, option)
> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]:   File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]:     raise NoSectionError(section)
> Jul 23 16:52:03 j-mint /lib/security/howdy/pam.py[19900]: NoSectionError: No section: 'core'
> 

This is all I changed:  

```
# Import required modules
import subprocess
import os
import glob
import syslog
import sys

# The config parser is named in python2 as ConfigParser but in python3 as configparser
# and here is a workaround for this.
if sys.version_info[0] == 2:
    import ConfigParser
    config = ConfigParser.ConfigParser()
else:
    import configparser
    config = configparser.ConfigParser()
 
 # Read config from disk
    config.read(os.path.dirname(os.path.abspath(__file__)) + "/config.ini")
```

I followed [this](https://github.com/boltgolt/howdy/issues/927#issue-2336395601) post and changed the **pam.py** to what is listed in his issue and now I get these errors. I am new to python and don't quite understand what I need to be fixing. Is it the config.ini file?

Howdy version (`sudo howdy version`): 2.6.1

**Comment by jordanss1** [comment]
Closing this. Modified a few lines in the pam.py file and it's all working now!
