### ISSUE TITLE
Howdy add issue

### ISSUE THREAD

**Issue by Setu7700** [boltgolt/howdy#963]
howdy snapshot
Traceback (most recent call last):
  File "/usr/local/bin/howdy", line 109, in <module>
    import cli.snap
  File "/lib/security/howdy/cli/snap.py", line 7, in <module>
    import snapshot
  File "/lib/security/howdy/snapshot.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

please help me to fix this  issue in details. i am new in linux. 

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable): linux mint

Howdy version (`sudo howdy version`):2.6.1

**Comment by boltgolt** [comment]
Do a reinstall, OpenCV was not correctly installed on your system
