### ISSUE TITLE
Big Python Update today - "No dlib"

### ISSUE THREAD

**Issue by Hamster1962** [boltgolt/howdy#978]
My Howdy was working perfectly until a large update tonight. Lots of Python programs and Camera type updates.
Now when I try and use Howdy i get the error :-

Traceback (most recent call last):
File "/lib/security/howdy/compare.py", line 18, in
import dlib
ModuleNotFoundError: No module named 'dlib'
Exact same error as 18 Months ago which was fixed by a further update.
Restoring a Snapshot solves the issue until the next update is run

I've searched for similar issues already, and my issue has not been reported yet. Yes

Linux distribution = Garuda Linux based on Arch with KDE Desktop Kernel 6.6.63-1-cachyos-lts

Howdy version (sudo howdy version): Howdy 3.0.0 BETA

Thanks for any help in advance.

**Comment by gguman** [comment]
If you are an Arch user with yay: yay -S --rebuildtree howdy-beta-git

**Comment by L-28** [comment]
At least with me that didn't work. `sudo howdy test` still results in:
```
Traceback (most recent call last):
  File "/usr/lib/howdy/cli.py", line 117, in <module>
    import cli.test
  File "/usr/lib/howdy/cli/test.py", line 10, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'

```

**Comment by Hamster1962** [comment]
No sadly. I run all the updates. Howdy returns the above error. My install of yay won't accept the argument --rebuildtree.
I did remove and re-install dlib (a reinstall won't & didn't work). A new install of dlib works but returns an error -
~~~
Exception ignored in: <_io.BufferedWriter name=4> 
BrokenPipeError: [Errno 32] Broken pipe
~~~
So Howdy works but with an error, there is a problem somewhere.

**Comment by gguman** [comment]
I confirm that there is an exception arise, but the howdy works.

**Comment by L-28** [comment]
In my case howdy doesn't work, it simply exits after the error/let's the next available unlock method take over

**Comment by Hamster1962** [comment]
Both the ideas above fix the initial error but the problems still exist because of the Pipe Error
~~~
Exception ignored in: <_io.BufferedWriter name=4> 
BrokenPipeError: [Errno 32] Broken pipe
~~~

**Comment by gguman** [comment]
The error text contains information that the exception was ignored, so it should not break the script. But it is very annoying to see it every time, but I can not find the error location in the source files

**Comment by connor-belli** [comment]
Rebuilding python-dlib fixed the issue for me

**Comment by mj1911** [comment]
Arch / Manjaro / Mabox recently bumped up their system python version, which broke many things, including old builds of howdy.  Solution is to `pamac remove howdy && pamac install howdy` which will purge everything and rebuild it, which then results in `AttributeError: 'VideoCapture' object has no attribute 'internal'` due to `/lib/security/howdy/config.ini` being reset.  Must then edit and set your video source, see https://wiki.archlinux.org/title/Howdy for more info.  I also had to manually define `frame_width` and height for a webcam.  So if you haven't tried (complete) rebuild/reinstall/reconfig yet, give that a shot.

**Comment by Hamster1962** [comment]
Just an idea, the developer of Howdy seems to be not maintaining it anymore. But another Distro, Deepin Linux, comes pre-built with facial recognition, maybe someone could take a look at Deepin and see how the facial recognition works and separate it out into a stand-alone app?

**Comment by Hamster1962** [comment]
I see you are working through the issues, Thanks, hopefully you can get to this one.
